"""empty message

Revision ID: c7534991798c
Revises: 98e4c106a894
Create Date: 2023-04-22 16:47:42.734231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7534991798c'
down_revision = '98e4c106a894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('eye_color', sa.String(length=15), nullable=True),
    sa.Column('hair_color', sa.String(length=15), nullable=True),
    sa.Column('home_world', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('height', sa.String(length=20), nullable=True),
    sa.Column('weight', sa.String(length=20), nullable=True),
    sa.Column('skin_color', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('character')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('eye_color', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('hair_color', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('home_world', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('height', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('weight', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('skin_color', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='character_pkey')
    )
    op.drop_table('people')
    # ### end Alembic commands ###
